---
- name: MySQL server setup using Ansible (no galaxy modules)
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: "ExpenseApp@1"
    mysql_public_ip: "34.224.214.45"
    mysql_private_ip: "172.31.24.47"

  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: Enable and start MySQL service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: Allow MySQL remote connections (update bind-address)
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify: Restart MySQL

    - name: Set MySQL root password and enable remote access
      ansible.builtin.shell: |
        mysql -u root <<EOF
        ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';
        CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '{{ mysql_root_password }}';
        GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
        EOF
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Restart MySQL service after configuration
      ansible.builtin.service:
        name: mysql
        state: restarted

    - name: Display connection details
      ansible.builtin.debug:
        msg:
          - "MySQL Public IP: {{ mysql_public_ip }}"
          - "MySQL Private IP: {{ mysql_private_ip }}"
          - "Root password: {{ mysql_root_password }}"
          - "Remote access: ENABLED (bind-address = 0.0.0.0)"
  
  handlers:
    - name: Restart MySQL
      ansible.builtin.service:
        name: mysql
        state: restarted
