---
- name: mysql-server setup using ansible
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: "ExpenseApp@1"
    login_host: "34.224.214.45"

  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: Enable and start MySQL service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: Gather MySQL server information
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: "{{ login_host }}"
      register: mysql_info
      ignore_errors: true

    - name: Display MySQL info
      ansible.builtin.debug:
        var: mysql_info
